Import ('env')

sources = Glob('*.cc')

result = env.StaticLibrary ('wepa_mock', sources);

pwd = Dir ('.').abspath;
current_directory = str (pwd);
env.Append (LIBPATH = [current_directory])

#Return ('result')

