language: cpp
script: cmake . && make && ctest --output-on-failure

before_script: 
   - sudo apt-get -qq update
   - sudo apt-get install -y libxml2-dev libboost-filesystem-dev libgtest-dev libsqlite3-dev sqlite sqlite3 libzmqpp-dev 

   
#
# Build Matrix
# 
matrix: 
    include:

    - os: linux
      env:
        - TEST="Codecov"
      script:
        - mkdir -p libs && cp -r /usr/src/gtest libs && cd libs/gtest && cmake . && make -j 2 && cd -
        - cmake -DCMAKE_BUILD_TYPE=COVERAGE 
        - make --jobs=4 && ctest --verbose
        - bash <(curl -s https://codecov.io/bash)

