dist: xenial
group: travis_lts

language: cpp
script: cmake . && make && make test

before_script: 
   - sudo apt-get -qq update
   - sudo apt-get install -y libxml2-dev libboost-filesystem-dev libboost-test-dev libsqlite3-dev:amd64 sqlite sqlite3
   
