debug = ARGUMENTS.get ('debug', 0)

Import ('env')

# See http://stackoverflow.com/questions/4693826/scons-binary-directory
if int(debug):
    result = SConscript ('SConscript', exports='env', variant_dir="debug")
else:
    result = SConscript ('SConscript', exports='env', variant_dir="release")

Return ('result')

