Import ('env')

# See http://www.scons.org/doc/2.0.1/HTML/scons-user/c1809.html
# about merging flags
boost_library = { 'LIBS' : 'boost_unit_test_framework' }
env.MergeFlags (boost_library)

env.Append (LIBPATH = '/usr/lib/x86_64-linux-gnu')

coffee_library = { 'LIBS' : ['coffee_logger', 'coffee_adt',  'coffee_config', 'coffee_app', 'coffee_xml', 'coffee_balance', 'coffee_dbms', 'coffee_dbms_sqlite', 'sqlite3'] }
env.MergeFlags (coffee_library)

pwd = Dir ('.').abspath;
current_directory = str (pwd);

libpath = current_directory.replace ('test/', 'source/');
env.Append (LIBPATH = [libpath])

result = env.Program ('coffee_dbms_sqlite_test', Glob ('*.cc'))

Return ('result')
