Import ('env')

sources = Glob('*.cc')
sources.extend (Glob('datatype/*.cc'))
sources.extend (Glob('binder/*.cc'))
sources.extend (Glob('internal/*.cc'))

result = env.StaticLibrary ('coffee_dbms', sources);

Return ('result')

