Import ('env')

# See http://www.scons.org/doc/2.0.1/HTML/scons-user/c1809.html
# about merging flags
boost_library = { 'LIBS' : [ 'boost_unit_test_framework', 'boost_filesystem' ] }
env.MergeFlags (boost_library)

wepa_library = { 'LIBS' : [ 'xml2', 'wepa_xml', 'wepa_logger', 'wepa_adt',  'wepa_config' ] }
env.MergeFlags (wepa_library)

pwd = Dir ('.').abspath;
current_directory = str (pwd);

libpath = current_directory.replace ('test/', 'source/');
env.Append (LIBPATH = [libpath])

result = env.Program ('wepa_xml_test', Glob ('*.cc'))

Return ('result')
