Import ('env')

# See http://www.scons.org/doc/2.0.1/HTML/scons-user/c1809.html
# about merging flags
boost_library = { 'LIBS' : 'boost_unit_test_framework' }
env.MergeFlags (boost_library)

# Set coffee_dbms twice to avoid linker dependences
coffee_library = { 'LIBS' : [  'coffee_config', 'coffee_adt', 'coffee_logger', 'coffee_xml', 'coffee_app', 'coffee_balance', 'coffee_dbms',  'coffee_persistence', 'coffee_dbms', 'coffee_app'  ] }
env.MergeFlags (coffee_library)

pwd = Dir ('.').abspath;
current_directory = str (pwd);

libpath = current_directory.replace ('test/', 'source/');
env.Append (LIBPATH = [libpath])

result = env.Program ('coffee_persistence_test', Glob ('*.cc'))

Return ('result')
