Import ('env')

# See http://www.scons.org/doc/2.0.1/HTML/scons-user/c1809.html
# about merging flags
boost_library = { 'LIBS' : 'boost_unit_test_framework' }
env.MergeFlags (boost_library)

wepa_library = { 'LIBS' : [ 'wepa_logger', 'wepa_adt',  'wepa_config', 'wepa_app', 'wepa_xml', 'wepa_balance', 'wepa_persistence', 'wepa_dbms' ] }
env.MergeFlags (wepa_library)

pwd = Dir ('.').abspath;
current_directory = str (pwd);

libpath = current_directory.replace ('test/', 'source/');
env.Append (LIBPATH = [libpath])

result = env.Program ('wepa_persistence_test', Glob ('*.cc'))

Return ('result')
