Import ('env')

sources = Glob('*.cc')
sources.extend (Glob('pattern/*.cc'))
sources.extend (Glob('pattern/observer/*.cc'))

print sources

result = env.StaticLibrary ('wepa_adt', sources);

Return ('result')

